# Generated by Django 4.1.5 on 2023-02-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
