# Generated by Django 4.1.5 on 2023-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errors',
            old_name='data',
            new_name='data_errors',
        ),
    ]
