# Generated by Django 4.1.5 on 2023-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_rename_data_errors_data_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=1250, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=1250, verbose_name='Vacancy title'),
        ),
    ]
